---
title: "IS609 - Networked Game Theory - Final Project"
author: "J. Hamski, S. Hong, H. Berk"
date: "April 9, 2016"
output: html_document
---

```{r}
library(igraph)
library(ggplot2)
```

Iterated Prisoner's Dilemma on a Graph.

The classic two person Prisoner's Dilemma. 

```{r}
nodes <- 20
degree <- 2
g.1 <- degree.sequence.game(rep(degree, nodes), method =  "vl")

#randomply select strategy
# 1 = defect, 2 = cooperate
V(g.1)$strategy <- sample(c(1,2), size = length(V(g.1)), replace = T)

V(g.1)[strategy == 1]$color <- 'red' # defect
V(g.1)[strategy == 2]$color <- 'blue' # cooperate
```

```{r}
plot(g.1)
```


Need to re-write this - it doesn't take into account the player's strategy, only the opponents!
```{r}
network.evaluation <- function(g){
  network.results <- NULL
  
  for(i in 1:nodes){
    
    opponents <- neighbors(g, i, mode="all")
    opponent.results <- NULL
    
    for(j in 1:length(opponents)){
      opponent.results <- c(opponent.results, opponents[j]$strategy)
    }
    # rbind isn't going to work when nodes have different number of edges
    network.results <- rbind(network.results, opponent.results)
  }
  return(network.results)
}
```


```{r}
game.evaluation <- function(results, nodes, g){
  row.names(results) <- 1:nodes
  results <- cbind(results, V(g)$strategy)
  
  sentence.list <- NULL
  
  for(i in 1:length(PD.results[,1])){
    if(results[i,1] == 1){ #row defects
        opponent.sum <- sum(results[i,-1])
        if(opponent.sum == 2){sentence.list = c(sentence.list, 0)}
        if(opponent.sum == 3){sentence.list = c(sentence.list, 6)}
        if(opponent.sum == 4){sentence.list = c(sentence.list, 12)}
    }
    else{
        opponent.sum <- sum(results[i,-1])
        if(opponent.sum == 2){sentence.list = c(sentence.list, 1)}
        if(opponent.sum == 3){sentence.list = c(sentence.list, 4)}
        if(opponent.sum == 4){sentence.list = c(sentence.list, 8)}
    }
  }
  return(sentence.list)
}
```


```{r}
r <- network.evaluation(g.1)
r.list <- game.evaluation(r, nodes, g.1)
```


```{r}
results.graph <- function(results.list, nodes, g){
  for(i in 1:nodes){
    V(g)[i]$result <- results.list[i]
  }
  return(g)
}
```

```{r}
g.results <- results.graph(r.list, nodes, g.1)
```



```{r}
V(g.1)[result == 1]$color <- 'green' # defect
V(g.1)[result == 2]$color <- 'purple' # cooperate
```


```{r}
plot(g.1)
```

```{r}
plot(V(g.1)$strategy)
```

```{r}
plot(V(g.1)$result)
```




```{r}
PD.results.opponents <- network.evaluation(g.1)
row.names(PD.results.opponents) <- 1:4
PD.results <- cbind(V(g.1)$strategy, PD.results.opponents)
colnames(PD.results)[1] <- "Row.Strategy"  

sentence.list <- NULL

for(i in 1:length(PD.results[,1])){
    if(PD.results[i,1] == 1){ #row defects
        opponent.sum <- sum(PD.results[i,-1])
        if(opponent.sum == 2){sentence.list = c(sentence.list, 0)}
        if(opponent.sum == 3){sentence.list = c(sentence.list, 6)}
        if(opponent.sum == 4){sentence.list = c(sentence.list, 12)}
    }
    else{
        opponent.sum <- sum(PD.results[i,-1])
        if(opponent.sum == 2){sentence.list = c(sentence.list, 1)}
        if(opponent.sum == 3){sentence.list = c(sentence.list, 4)}
        if(opponent.sum == 4){sentence.list = c(sentence.list, 8)}
    }
  }


```

