---
title: "Network Logic Sketching"
author: "James Hamski"
date: "April 14, 2016"
output: html_document
---
##*Demo from:*  
http://chengjun.github.io/en/2014/03/simulate-network-diffusion-with-R/  
```{r, message=F, warning=F}
library(igraph)
library(dplyr)
```

```{r}
size = 10

g <- graph.tree(size, children = 2)
plot(g)
```

```{r}
g <- graph.star(size)
plot(g)
```

```{r}
g <- graph.full(size)
plot(g)
```

```{r}
g <- graph.ring(size)
plot(g)
```

```{r}
g <- connect.neighborhood(graph.ring(size), 2)
plot(g)
```

Random network
```{r}
g <- erdos.renyi.game(size, 0.1)
plot(g)
```

```{r}
#g <- rewire.edges(g, prob = 0.8)
```
### Generate the network  

Scale-free network
```{r}
size = 50
node_number = size

g <- barabasi.game(size)
plot(g)
```

### Initiate the diffusers

```{r}
seeds_num = 1
set.seed(2014); diffusers = sample(V(g),seeds_num) ; diffusers
infected =list()
infected[[1]]= diffusers
```

```{r}
# for example, set percolation probability 
transmission_rate = 0.4
coins = c(1, 0) 
probabilities = c(transmission_rate, 1-transmission_rate )         
# sample(coins, 1, rep=TRUE, prob=probabilities) # Generate a sequence
# toss the coins
toss = function(freq) {
  tossing = NULL
  for (i in 1:freq ) tossing[i] = sample(coins, 1, rep=TRUE, prob=probabilities)
  tossing = sum(tossing)
  return (tossing)
}
```

```{r}
update_diffusers = function(diffusers){
    nearest_neighbors = data.frame(table(unlist(neighborhood(g, 1, diffusers))));
    nearest_neighbors = subset(nearest_neighbors, !(nearest_neighbors[,1]%in%diffusers))
    keep = unlist(lapply(nearest_neighbors[,2], toss))
    new_infected = as.numeric(as.character(nearest_neighbors[,1][keep >= 1]))
    class(new_infected) <- "igraph.vs"
    diffusers = unique(c(diffusers, new_infected))
    return(diffusers)
}
```

```{r}
total_time = 1
while(length(infected[[total_time]]) < node_number){ 
  infected[[total_time+1]] = sort(update_diffusers(infected[[total_time]]))
  cat(length(infected[[total_time+1]]), "-->")
  total_time = total_time + 1
}

```

```{r}
plot_time_series = function(infected, m){
  num_cum = unlist(lapply(1:m, 
                          function(x) length(infected[[x]]) ))
  p_cum = num_cum/node_number
  p = diff(c(0, p_cum))
  time = 1:m
  plot(p_cum~time, type = "b", 
       ylab = "CDF", xlab = "Time",
       xlim = c(0,total_time), ylim =c(0,1))
}

```

```{r}
plot_time_series(infected, length(infected))

```

